### PR TITLE
Stores non-volatile state with akka-persistence

### LINKED ISSUE #62: Any exception can cause two leaders to become elected in the same Term
The Raft protocol assumes a crash-recovery failure model -- that is, it allows for the possibility that crashed nodes will come back (with non-volatile state intact).

Currently, akka-raft does not write anything to disk. That's actually fine -- it just means that akka-raft currently assumes a crash-stop failure model, where crashed nodes are never allowed to come back.

However, akka-raft should enforce crash-stop! It currently does not, and this can lead to problems. 

More specifically:

By [default](http://doc.akka.io/docs/akka/snapshot/scala/fault-tolerance.html), akka's supervision strategy restarts any actor that throws an exception. When it restarts, all its state is reinitialized.

In the Raft paper, the `votedFor` variable is listed as persistent (non-volatile) state on each server. If `votedFor` is forgotten, a node may end up voting for two different candidates in the same term.

If RaftActor throws an exception for any reason, it may end up in the situation where it eventually votes for two different candidates in the same, possibly causing two different leaders to be elected.

I see two solutions:
  - Either write to disk
  - or force `akka.actor.guardian-supervisor-strategy = akka.actor.StoppingSupervisorStrategy`, so that nodes do not recover

I discovered this bug because one of my recent fixes accidentally triggered an exception -- and later in my fuzz run I saw that two leaders became elected in the same term.

### PR DESCRIPTION
**Pull request by dmitraver**
Fixes #62 

Hi! 

I decided to make a PR with my change as "is" because fixing the tests is a really huge task that I think should be addressed separately. I actually tried to fix the tests by changing all references from TestFsmRef/TestActorRef to normal raft actors but I stuck on rewriting "unit" tests for Follower/Leader/Candidate. When I mixin EventStreamAllMessages into actor I get 
_Unhandled message ... in state Init_ and it looks like actor stuck after that until my assertion is fired due to timeout. I don't see any log messages after. Also I'm not quite sure that its possible to keep the tests mentioned above as they are cause they are testing some responses to messages in a concrete state and its hardly possible to make this assertions reliable when you have the whole cluster on nodes where state is constantly changing. Anyway, I will continue to work on this and try to figure it out :)

### CODE REVIEW

**Comment by dmitraver** [comment]
@ktoso Could you please take a look at this once you have time. I'm also thinking about adding snapshotting support as it can improve replay of the states on a startup.

**Comment by dmitraver** [comment]
@ktoso Hi! Are you considering merging it at some point? I've started working on test improvements for this change.

**Comment by ktoso** [comment]
Hi there,
I'm happy to merge things here but am not actively looking here so things may slip my attention.
Please ping me if something keeps hanging around being inactive like here :)

I'll give it a look and definitely happy to accept more PRs!

**Comment by dmitraver** [comment]
Happy to hear that! More PRs are coming :)

**Comment by ktoso** [comment]
I've looked through, as a next step it would be nice to have a Spec that kills the ActorSystem unexpectedly and see that a node can actually properly recover from the persistent state :)

**Comment by dmitraver** [comment]
@ktoso Awesome! Thank you :) I'm working on that. However, have some difficulties rewriting existing tests. I think its hardly possible to test concrete actor states like candidate/follower/leader using probes as the actors are changing their state very fast in non-deterministic way. Can you suggest something for the problem?

**Comment by ktoso** [comment]
One technique is to use the event stream with the state informations: http://www.blog.project13.pl/index.php/fun/1915/testing-leader-election-in-raft-using-akka-without-thread-sleep/

Another is to subscribe to transition events of the FSMs: http://doc.akka.io/docs/akka/2.4.7/scala/fsm.html#External_Monitoring

**Comment by dmitraver** [comment]
Nice, I will take a look at it then. Thx.

**Pull request merged**
